import random
BOT_RESPONSES = {

    "BOOK_FLIGHT": [
        "Sure, I can book your flight. Please provide your source city, destination city, and travel date.",
        "I’ll help you book a flight. Tell me your departure city, arrival city, and date of travel.",
        "Let’s get started with your flight booking. What is your source city, destination city, and travel date?",
        "I can assist with booking your flight. Please share your source, destination, and preferred date.",
        "To book your flight, I need your source city, destination city, and journey date.",
        "Flight booking is available. Kindly provide the source city, destination city, and travel date.",
        "I’m ready to book your flight. Where are you flying from, where to, and on which date?",
        "Please tell me your source city, destination city, and travel date so I can book your flight.",
        "I can proceed with booking your flight once you provide source, destination, and date.",
        "To continue with flight booking, please share your departure city, arrival city, and travel date.",
        "Let me book your flight. I need the source city, destination city, and date of travel.",
        "Flight booking request received. Please provide your source city, destination city, and date.",
        "I can arrange your flight. Tell me your departure city, arrival city, and journey date.",
        "Please share your source city, destination city, and travel date to book the flight.",
        "I’m happy to book your flight. Where are you traveling from, where to, and when?",
        "To start booking, I need your source city, destination city, and date of travel.",
        "I can book your airline ticket. Please provide source city, destination city, and date.",
        "Flight booking assistance activated. Share your source, destination, and travel date.",
        "Let’s book your flight. Please tell me your source city, destination city, and date.",
        "I’m ready to proceed. Provide your departure city, arrival city, and travel date."
    ],

    "CANCEL_BOOKING": [
        "I can help you cancel your booking. Please provide your flight number or ticket number.",
        "Sure, I’ll assist with cancellation. Kindly share your flight number or ticket number.",
        "To cancel your booking, please provide your ticket number or flight number.",
        "Cancellation request noted. I need your flight number or ticket number to proceed.",
        "Please share your flight number or ticket number so I can cancel your booking.",
        "I can cancel your flight. Kindly provide the flight number or ticket number.",
        "To proceed with cancellation, please tell me your flight number or ticket ID.",
        "I’ll help you cancel the booking once you provide the flight number or ticket number.",
        "Please confirm your flight number or ticket number for cancellation.",
        "Your cancellation request is received. Share your flight number or ticket number.",
        "To cancel your reservation, I need your flight number or ticket reference.",
        "Kindly provide your ticket number or flight number to cancel the booking.",
        "I’m ready to process the cancellation. Please share your flight number or ticket number.",
        "Cancellation can be processed after you provide the flight number or ticket number.",
        "Please tell me your ticket number or flight number to continue cancellation.",
        "I can assist further once you provide your flight number or ticket number.",
        "To cancel your flight, please provide the ticket number or flight number.",
        "Your booking can be cancelled. Kindly share your flight number or ticket ID.",
        "Please provide your flight number or ticket number so I can proceed.",
        "Cancellation support is active. Share your flight number or ticket number."
    ],

    "FLIGHT_DETAILS": [
        "I can fetch flight details for you. Please provide the flight number.",
        "Sure, please share the flight number to view flight details.",
        "To get flight details, kindly provide the flight number.",
        "Please tell me the flight number so I can show you the details.",
        "Flight details can be retrieved using the flight number. Please share it.",
        "I’m ready to show flight information. Provide the flight number.",
        "To check flight details, please enter the flight number.",
        "I need the flight number to display flight details.",
        "Please provide your flight number to get the flight information.",
        "Flight details request received. Kindly share the flight number.",
        "I can show flight timing and status. Please provide the flight number.",
        "To proceed, I need the flight number for which you want details.",
        "Please share the flight number so I can fetch the details.",
        "I’ll get the flight details once you provide the flight number.",
        "Kindly tell me your flight number to continue.",
        "Flight information is available. Please provide the flight number.",
        "I need the flight number to retrieve flight details.",
        "Please enter the flight number to view flight information.",
        "To view flight details, kindly provide the flight number.",
        "Share the flight number so I can display the flight details."
    ],

    "TICKET_DETAILS": [
        "I can show your ticket details. Please provide the flight number.",
        "Sure, please share the flight number to view ticket details.",
        "To fetch ticket details, kindly provide the flight number.",
        "Please tell me the flight number to see your ticket details.",
        "Ticket details can be retrieved using the flight number. Please share it.",
        "I need the flight number to show ticket information.",
        "Provide the flight number so I can display ticket details.",
        "Please enter your flight number to view ticket details.",
        "I can fetch ticket details once you provide the flight number.",
        "Ticket details request received. Kindly share the flight number.",
        "To proceed, I need the flight number for ticket details.",
        "Please share the flight number to continue.",
        "I’m ready to display ticket details. Provide the flight number.",
        "Ticket information is available. Please provide the flight number.",
        "To view your ticket details, kindly enter the flight number.",
        "Please tell me your flight number so I can show ticket details.",
        "I can help with ticket details. Share the flight number.",
        "Kindly provide the flight number to fetch ticket information.",
        "I need your flight number to retrieve ticket details.",
        "Enter the flight number to view ticket details."
    ],

    "PAYMENT_STATUS": [
        "I can check your payment status. Please provide your ticket number or flight number.",
        "Sure, please share your ticket number or flight number to check payment status.",
        "To verify payment status, kindly provide the ticket number or flight number.",
        "Please tell me your flight number or ticket number to check payment details.",
        "Payment status can be checked using your ticket number or flight number.",
        "I need your ticket number or flight number to verify payment status.",
        "Please provide your flight number or ticket number for payment confirmation.",
        "I can check payment details once you share the ticket number or flight number.",
        "Payment status request received. Kindly provide the ticket number or flight number.",
        "To proceed, I need your ticket number or flight number.",
        "Please share your flight number or ticket number to continue.",
        "I’m ready to check your payment status. Provide ticket or flight number.",
        "Payment verification requires your ticket number or flight number.",
        "Please enter your ticket number or flight number to check payment.",
        "I can retrieve payment information with your ticket number or flight number.",
        "Kindly share your ticket number or flight number for payment status.",
        "To view payment status, please provide flight number or ticket number.",
        "I need your flight number or ticket number to fetch payment details.",
        "Please confirm your ticket number or flight number for payment verification.",
        "Payment status is available once you provide ticket or flight number."
    ]
}



